FEATURE(redis): Allow to use AOF
open-io/ansible-role-openio-redis pull request #27
Opened 2020-01-14 13:54 UTC by cdelgehier

##### SUMMARY

By default Redis asynchronously dumps the dataset on disk.
This mode is good enough, but an issue with the Redis process may result into a few minutes of writes lost (depending on the configured save points).

The Append Only File is an alternative persistence mode that provides much better durability.

AOF and RDB persistence can be enabled at the same time without problems.

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION
OS-471

2020-01-14 14:10 UTC, cdelgehier commented
```
TASK [role_under_test : set slave status on bootstrap] *************************
Tuesday 14 January 2020  14:02:31 +0000 (0:00:00.045)       0:01:44.863 ******* 
FAILED - RETRYING: set slave status on bootstrap (5 retries left).
FAILED - RETRYING: set slave status on bootstrap (4 retries left).
FAILED - RETRYING: set slave status on bootstrap (3 retries left).
FAILED - RETRYING: set slave status on bootstrap (2 retries left).
FAILED - RETRYING: set slave status on bootstrap (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectionError: Error 111 connecting to 172.17.0.4:6011. Connection refused.
fatal: [localhost]: FAILED! => changed=false 
  attempts: 5
  msg: 'unable to connect to database: Error 111 connecting to 172.17.0.4:6011. Connection refused.
```
![bitmoji](https://render.bitstrips.com/v2/cpanel/c3bd1c53-57b5-43b0-9b0a-444ceb41ad35-0c2e4917-c514-46b4-81aa-9a122eb9bad8-v1.png?transparent=1&palette=1&width=246)

2020-01-28 09:22 UTC, sebastienlapierre approved these changes
Well done

2020-01-28 09:25 UTC, fatpat requested changes
The `inpact` section of your commit message should not be `N/A` as this PR changes the default behavior by enabling `ADB`. Same applies for the timeout change which rise from 1s to 5s. I don't think it's a good idea to change it or at least write a warning about it in the commit message.

plus my comments on the code:
- some options requires redis >= 4 (how is it handled ?)
- why raising the default timeout from 1s to 5s ? 1s was fine to me but 5s seems a bit high

2020-01-28 09:25 UTC, fatpat commented on README.md
> +| `openio_redis_aof_use_rdb_preamble` | `"yes"` | Allow Redis to use an RDB preamble in the AOF file for faster rewrites and recoveries |
dispo uniquement à partir de `redis >= 4.0`

2020-01-28 09:25 UTC, fatpat commented on README.md
> +| `openio_redis_down_after` | `5000` | Number of milliseconds the master (or any attached slave or sentinel) should be unreachable |
why to rise the timeout from 1s to 5s ?

2020-01-28 10:18 UTC, fatpat approved these changes

2020-01-28 10:30 UTC, merged